//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerialPortIO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SerialPortIO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?AZ&lt;0.
        /// </summary>
        internal static string AutoZeroStatus {
            get {
                return ResourceManager.GetString("AutoZeroStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALIBRATE.
        /// </summary>
        internal static string Calibrate {
            get {
                return ResourceManager.GetString("Calibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?INTEXT.
        /// </summary>
        internal static string CalLeakRef {
            get {
                return ResourceManager.GetString("CalLeakRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?CL-XFER.
        /// </summary>
        internal static string ContraModeXoverPressure {
            get {
                return ResourceManager.GetString("ContraModeXoverPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?CPLOCKOUT.
        /// </summary>
        internal static string ControlPanelLockStatus {
            get {
                return ResourceManager.GetString("ControlPanelLockStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?CURRDATE.
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?DISPLAY.
        /// </summary>
        internal static string DisplayBarGraphFormat {
            get {
                return ResourceManager.GetString("DisplayBarGraphFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?DB.
        /// </summary>
        internal static string DisplayBoardStatus {
            get {
                return ResourceManager.GetString("DisplayBoardStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?EMISSION.
        /// </summary>
        internal static string Emission {
            get {
                return ResourceManager.GetString("Emission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?EXPONENT.
        /// </summary>
        internal static string ExponentNumber {
            get {
                return ResourceManager.GetString("ExponentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?EXTLEAK.
        /// </summary>
        internal static string ExtCalLeakValue {
            get {
                return ResourceManager.GetString("ExtCalLeakValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXTERNAL.
        /// </summary>
        internal static string ExternalLeakStd {
            get {
                return ResourceManager.GetString("ExternalLeakStd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?GAIN.
        /// </summary>
        internal static string Gain {
            get {
                return ResourceManager.GetString("Gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?INTEXT.
        /// </summary>
        internal static string GetIntOrExtLeakStd {
            get {
                return ResourceManager.GetString("GetIntOrExtLeakStd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KEEP.
        /// </summary>
        internal static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ZERO.
        /// </summary>
        internal static string Zero
        {
            get
            {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to INIT-EXTLEAK.
        /// </summary>
        internal static string InitExtLeak {
            get {
                return ResourceManager.GetString("InitExtLeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?IONCHAMBER.
        /// </summary>
        internal static string IonChamber {
            get {
                return ResourceManager.GetString("IonChamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?CALOK.
        /// </summary>
        internal static string IsCalOK {
            get {
                return ResourceManager.GetString("IsCalOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?LANGUAGE.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?CALOK.
        /// </summary>
        internal static string LastCalStatus {
            get {
                return ResourceManager.GetString("LastCalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?LEAK.
        /// </summary>
        internal static string LeakRate {
            get {
                return ResourceManager.GetString("LeakRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOSNIFF.
        /// </summary>
        internal static string NoSniff {
            get {
                return ResourceManager.GetString("NoSniff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?OFFSET.
        /// </summary>
        internal static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?EXTLEAK.
        /// </summary>
        internal static string ReadExtLeakVal {
            get {
                return ResourceManager.GetString("ReadExtLeakVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROUGH.
        /// </summary>
        internal static string Rough {
            get {
                return ResourceManager.GetString("Rough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?EEPTYPE.
        /// </summary>
        internal static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XYZZY.
        /// </summary>
        internal static string UnlockFullCommand {
            get {
                return ResourceManager.GetString("UnlockFullCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?VALVESTATE.
        /// </summary>
        internal static string ValveState {
            get {
                return ResourceManager.GetString("ValveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VENT.
        /// </summary>
        internal static string Vent {
            get {
                return ResourceManager.GetString("Vent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .EEVGAIN.
        /// </summary>
        internal static string VGain {
            get {
                return ResourceManager.GetString("VGain", resourceCulture);
            }
        }
    }
}
